version: 1
repos:
  - repo: debian
    from: oci
    ociConfig:
      platform: linux
      arch: x64

  # - repo: Sirherobrine23/ghcrAptRepository
  #   from: release

  # - repo: The-Bds-Maneger/BedrockFetch
  #   from: release

  # - repo: cli/cli
  #   from: release