apt-config:
  portListen: 3000
  enableHash: true
  saveFiles: true
  pgpKey:
    private: ./private.key
    public: ./public.key
repositories:
  nodejs:
    targets:
    - from: mirror
      uri: https://deb.nodesource.com/node_19.x
      dists:
        bullseye:
          suites:
          - main
  github:
    apt-config: {}
    targets:
      - from: github_release
        repository: cli
        owner: cli
        tags:
        - v2.21.1
        - v2.21.0
      - from: github_release
        repository: desktop
        owner: shiftkey
        suite: main
        assetsLimit: 3
        cronRefresh:
          - 0/30 0 * * *
  APT_bysh23:
    apt-config: {}
    targets:
      - from: github_tree
        repository: APT_bysh23
        owner: Sirherobrine23
        tree: master
        suite: main
        path:
          - /package/main
          - path: /package/not-bysh23
            suite: not_by_sirherobrine
