# Global apt config
apt-config:
  origin: ""
  enableHash: true # if it is enabled, it may freeze the request a little because I have to wait for the hashes of the "Packages" files
  sourcesHost: http://localhost:3000
  # If you want to use a custom sources.list
  sourcesList: deb [trusted=yes] %s://%s %s main

repositories:
# Example to docker and OCI image
# - from: oci
#   image: ghcr.io/sirherobrine23/nodeaptexample
#   # Release endpoint config
#   apt-config:
#     origin: github.com/cli/cli
#     lebel: github-cli

# Example to github release
- from: github_release
  repository: cli
  owner: cli
  takeUpTo: 2