name: Publish docker nightly image
on:
  push:
    branches:
      - main

jobs:
  publishpackage:
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - uses: actions/checkout@v3
      name: Code checkout

    - name: Setup QEMU to Docker
      uses: docker/setup-qemu-action@v2

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login into registry Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      uses: docker/build-push-action@v4
      with:
        platforms: "linux/amd64,linux/arm64"
        context: ./
        push: true
        tags: ghcr.io/sirherobrine23/apt-stream:nightly
