name: Test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test"
    steps:
    - uses: actions/checkout@v3
      name: Code checkout

    # Install nodejs
    - uses: actions/setup-node@v3
      name: Setup node.js
      with:
        node-version: latest

    # Install dependecies
    - name: Install nodejs dependencies
      run: npm ci

    # Run test
    - name: Test
      run: npm run test